### ISSUE TITLE
Post data of `cpr::File` is different from a `cpr::Buffer` of the same file

### ISSUE THREAD

**Issue by vancer0** [libcpr/cpr#1105] opened 2024-09-06 15:59 UTC
### Description

When I try to upload a file within a `Multipart` with a `Post` request, the bytes are different when I use `cpr::File` and `cpr::Buffer` for the same file. Below is some example code I tried with a small PNG image.

```c++
// Using Buffer
std::vector<char> vec;
std::ifstream file("test.png");
std::copy(std::istream_iterator<char>(file), std::istream_iterator<char>(), std::back_inserter(vec));

cpr::Response res1 = cpr::Post(cpr::Url{"http://www.httpbin.org/post"},
                               cpr::Multipart{{"name", cpr::Buffer{vec.begin(), vec.end(), "test.png"}}});
std::cout << res1.text << std::endl;

// Using File
cpr::Response res2 = cpr::Post(cpr::Url{"http://www.httpbin.org/post"},
                               cpr::Multipart{{"name", cpr::File{"test.png"}}});
std::cout << res2.text << std::endl;
```

The output I get is this:
```json
{
  "args": {}, 
  "data": "", 
  "files": {
    "name": "<some data>"
  }, 
  "form": {}, 
  "headers": {
    ...
    "Content-Length": "25654", 
    "Content-Type": "multipart/form-data; boundary=------------------------7XWq6nScPC3xKHD7Jjb9z2", 
    "User-Agent": "curl/8.6.0-DEV", 
    ...
  }, 
  "json": null, 
  "origin": "...", 
  "url": "http://www.httpbin.org/post"
}

{
  "args": {}, 
  "data": "", 
  "files": {
    "name": "<different data>"
  }, 
  "form": {}, 
  "headers": {
    ...
    "Content-Length": "28374", 
    "Content-Type": "multipart/form-data; boundary=------------------------btaObLMBqn5Laa0AYu2ytO", 
    "User-Agent": "curl/8.6.0-DEV", 
    ...
  }, 
  "json": null, 
  "origin": "...", 
  "url": "http://www.httpbin.org/post"
}
```
You can also see that the lengths are different. Also I should mention that if I save the `vec` buffer back again into a file, it is identical to the original.

### Example/How to Reproduce

See code example

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS: Fedora Linux
- Kernel Version: 6.10.6
- cURL Version: 8.6.0 vcpkg

**Comment by aadit-n3rdy** [comment] 2024-10-05 18:34
Hey! I tried to investigate this issue and I found that it's because of the addition of a `Content-Type` field (specific to the file) when using `cpr::File`.  I checked the POST messages using netcat, and this is the difference I found.
- Using cpr::File:
```
POST / HTTP/1.1
Host: localhost:8080
User-Agent: curl/8.10.1
Accept: */*
Accept-Encoding: deflate, gzip
Content-Length: 233
Content-Type: multipart/form-data; boundary=------------------------Vcpz3MhfvzU7ffh1H7hQ8n

--------------------------Vcpz3MhfvzU7ffh1H7hQ8n
Content-Disposition: form-data; name="name"; filename="testfile"
Content-Type: application/octet-stream

hello world!
xyz
abc

--------------------------Vcpz3MhfvzU7ffh1H7hQ8n--

```
- Using cpr::Buffer:
```
POST / HTTP/1.1
Host: localhost:8080
User-Agent: curl/8.10.1
Accept: */*
Accept-Encoding: deflate, gzip
Content-Length: 193
Content-Type: multipart/form-data; boundary=------------------------vqMSmvbSiiPlT3Kz6RQPsL

--------------------------vqMSmvbSiiPlT3Kz6RQPsL
Content-Disposition: form-data; name="name"; filename="testfile"

hello world!
xyz
abc

--------------------------vqMSmvbSiiPlT3Kz6RQPsL--
```

Should the content-type be specified while using `cpr::Buffer` as well? If so is can I work on this? (adding a default Content-Type such as octet-stream)

**Comment by COM8** [comment] 2024-10-06 05:15
@aadit-n3rdy thanks for looking further into this issue!
To me with my limited experience in HTTP this looks correct and like expected.

A HTTP Multipart Form is structured differently than just dumping a binary blob (file) via POST.

**Comment by aadit-n3rdy** [comment] 2024-10-06 05:49
No problem!

Yeah, I don't think this is unexpected behaviour either, that's probably why httpbin parsed it right as well. That said is there a way to set the Content-Type field manually for a file while making a multipart request? I tried checking the documentation but I might've missed it.

**Comment by COM8** [comment] 2024-10-10 16:53
Closing this one as it does not seam to be a cpr issue.

**Closed by COM8** 2024-10-10 16:53 UTC
Labels: Bug :bug:, Needs Investigation :mag:
