### ISSUE TITLE
Content-Type after cpr::Buffer doesn't work

### ISSUE THREAD

**Issue by kkdiy** [libcpr/cpr#711] opened 2022-03-20 03:28 UTC
## Description

std::vector code{ 'h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd' };

			auto test = cpr::Multipart{
			 {"action", "update"},
			 {					
				 "file", cpr::Buffer{ code.begin(), code.end(),"test.txt"},"image/jpeg"
			 }
		    };
Content-Type after cpr::Buffer doesn't work

## Expected Behavior
Content-Type: image/jpeg

## Actual Behavior
Content-Type: text/text

## Steps to Reproduce
std::vector code{ 'h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd' };

			auto test = cpr::Multipart{
			 {"action", "update"},
			 {					
				 "file", cpr::Buffer{ code.begin(), code.end(),"test.txt"},"image/jpeg"
			 }
		    };

Content-Type: image/jpeg
1.
2.
3.
4.

## Your Environment

* Version used:
* Where did you get it from (e.g. conan, vcpkg, master, ...):
* Operating System and version:
* Link to a small example:

**Comment by COM8** [comment] 2022-03-20 06:07
So, in your response the Content-Type is text/text?

**Comment by kkdiy** [comment] 2022-03-20 07:04
Content-Type: application/octet-stream

**Comment by COM8** [comment] 2022-03-20 08:34
Where do you then expect `image/jpeg`?

**Comment by COM8** [comment] 2022-03-20 11:09
Duplicate of https://github.com/libcpr/cpr/issues/216

**Closed by COM8** 2022-03-20 11:09 UTC
