### ISSUE TITLE
Even with cpr::VerifySsl(false), HTTPS requests always return an empty string

### ISSUE THREAD

**Issue by WesThorburn** [libcpr/cpr#263] opened 2018-03-12 21:38 UTC
Sample Code:
```
auto r = cpr::Get(cpr::Url{ "https://youtube.com" },cpr::VerifySsl(false));
std::cout << r.url << std::endl; 
std::cout << r.status_code << std::endl; // 200
std::cout << r.text << std::endl;
```
Output:
```
https://youtube.com/
0


```
The above output is identical even if spr::VerifySsl(false) is removed. Request works fine if using HTTP. 

I'm running Ubuntu 16.04, 64 bit, however several of other users have been reporting this same issue on a variety of machines. 
[Issue 261](https://github.com/whoshuu/cpr/issues/261)
[Issue 254](https://github.com/whoshuu/cpr/issues/254)
[Issue 246](https://github.com/whoshuu/cpr/issues/246)
[Issue 222](https://github.com/whoshuu/cpr/issues/222)
[Issue 194](https://github.com/whoshuu/cpr/issues/194)

**Comment by Liastre** [comment] 2018-03-28 10:25
Hello, can you share the error you got? Class `Response` contains public member `error`, do `std::cout << r.error << std::endl;` to retrieve actual error you has.

**Comment by emrahayanoglu** [comment] 2018-06-05 10:06
I had the same issue and found the problem:
Accessing VerifySSL from global namespace doesn't change anything on the CURL attributes. 
You should use directly use session class to change verification of the SSL like below:

```
    auto url = cpr::Url{"http://www.httpbin.org/get"};
    auto parameters = cpr::Parameters{{"hello", "world"}};
    cpr::Session session;
    session.SetUrl(url);
    session.SetParameters(parameters);
    session.SetVerifySsl(false);
    
    auto r = session.Get();
```

**Comment by COM8** [comment] 2020-04-16 13:31
@emrahayanoglu could you create a PR for the `gh-pages` branche to update documentation for this please?

**Comment by Nullarity** [comment] 2023-04-01 16:50
Is this issue still relevant, or is CPR not supposed to work on Ubuntu (I tried two different versions)? I tried building and running an example from the homepage without success. The r.status_code for the provided example is 0 all the time.
-
Linux Mint 21, Ubuntu 20.04

**Comment by COM8** [comment] 2023-04-02 17:42
@Nullarity we even test against multiple different versions of Ubuntu in our CI to make sure everything works on Ubuntu (https://github.com/libcpr/cpr/blob/master/.github/workflows/ci.yml).

Usually behaviour like this is caused by wrong CA paths. What you could try is setting `CURL_CA_FALLBACK` like I have done it here:
https://github.com/COM8/home-ui/blob/dfa172c24a835d75c3940d5e9084b995cebf3b83/CMakeLists.txt#L110-L114

**Comment by COM8** [comment] 2023-04-02 17:43
You could also try passing `cpr::Verbose{true}` to a session (or a request) to get more debug output from curl. If you decide to do this, please post the output here.

**Comment by Nullarity** [comment] 2023-04-18 21:34
@COM8 Sorry for the late reply.
```cpr::Verbose{true}``` helped to identify this problem: ```Protocol "https" not supported or disabled in libcurl```.
I compiled openssl from source, then recompiled cpr and finally solved the problem.
Thanks for your help.

**Comment by COM8** [comment] 2023-04-22 12:32
Awesome. Great to hear @Nullarity !
Closing this issue for now. Feel free to open a new one in case anyone still has issues with it.

**Closed by COM8** 2023-04-22 12:32 UTC
Labels: Documentation :books:

**Comment by okadapy** [comment] 2023-06-08 20:22
Hello! Same issue for me. I got CPR from VCPKG, my OS is Manjaro Linux. 
Verbose doesn't show anything (or anything that im aware of)
curl returns a string that i've set to be returned, cpr doesnt. 


Code:
    nlohmann::json data;
    for (int i = 1; i+1 < line->size(); ++i) {
        if (line->at(i+1).find("https") == string::npos) {
            data[line->at(i)] = line->at(i+1);
        }
    }
    cout << data.dump() << endl;
    cpr::Response response = cpr::Post(cpr::Url{line->at(line->size()-1)},
                                        cpr::Body{data.dump()},
                                        cpr::VerifySsl(false));
    cout << response.text << endl;

Verbose output:
  * WARNING: failed to open cookie file ""
  *   Trying 
  * Connected to port 443 (#0)
  * ALPN: offers h2,http/1.1
  * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
  * ALPN: server accepted http/1.1
  * Server certificate:
  *  subject: CN=
  *  start date: May 22 14:14:12 2023 GMT
  *  expire date: Aug 20 14:14:11 2023 GMT
  *  issuer: C=US; O=Let's Encrypt; CN=R3
  *  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
  * using HTTP/1.1
  > POST /api HTTP/1.1
  Host: 
  User-Agent: curl/8.1.0
  Accept: */*
  Content-Length: 15
  Content-Type: application/x-www-form-urlencoded
  
  * old SSL session ID is stale, removing
  < HTTP/1.1 200 OK
  < Date: Thu, 08 Jun 2023 19:59:22 GMT
  < Server: Apache
  < Expires: Thu, 19 Nov 1981 08:52:00 GMT
  < Cache-Control: no-store, no-cache, must-revalidate
  < Pragma: no-cache
  < Access-Control-Allow-Origin: *
  < Access-Control-Allow-Headers: *
  < Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
  * Added cookie ci_sessions="ub3hs5frho0btgc18cei079l7u7b74k5" for domain , path /, expire 1686261541
  < Set-Cookie: ci_sessions=ub3hs5frho0btgc18cei079l7u7b74k5; expires=Thu, 08-Jun-2023 21:59:22 GMT; Max-Age=7200; path=/; domain=; HttpOnly
  < Upgrade: h2,h2c
  < Connection: Upgrade
  < Content-Length: 0
  < Content-Type: text/html; charset=UTF-8
  < 
  * Connection #0 to host  left intact

Curl:
   curl --data-urlencode "type=test"                                                                                                                                            
   AAAA

**Comment by COM8** [comment] 2023-06-09 16:49
Try replacing `cpr::Body` with `cpr::Payload`.

**Comment by dwstrong5** [comment] 2024-06-02 02:49
Similar issue here on Windows with Visual Studio. Using the sample code on the readme:

`#include <iostream>
#include <cpr/cpr.h>
#include <cpr/ssl_options.h>

int main(int argc, char** argv)
{   
    
    cpr::Response r = cpr::Get(cpr::Url{ "https://api.github.com/repos/whoshuu/cpr/contributors" },
        cpr::Authentication{ "user", "pass", cpr::AuthMode::BASIC },
        cpr::Parameters{ {"anon", "true"}, {"key", "value"} },
        cpr::VerifySsl(false),
        cpr::Verbose(true));
    r.status_code;                  // 200
    r.header["content-type"];       // application/json; charset=utf-8
    r.text;                         // JSON text string

    std::cout << r.status_code << std::endl;
    return 0;
}`

Output:
`
* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => SETUP handle 0x25df2218cd8; line 1971
* STATE: SETUP => CONNECT handle 0x25df2218cd8; line 1987
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x25df2218cd8; line 2013
* Host api.github.com:443 was resolved.
* IPv6: (none)
* IPv4: 140.82.112.5
* STATE: RESOLVING => CONNECTING handle 0x25df2218cd8; line 2087
*   Trying 140.82.112.5:443...
* Connected to api.github.com (140.82.112.5) port 443
* schannel: SSL/TLS connection with api.github.com port 443 (step 1/3)
* Didn't find Session ID in cache for host https://api.github.com:443
* schannel: disabled server cert revocation checks
* schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: sending initial handshake data: sending 280 bytes.
* schannel: sent initial handshake data: sent 280 bytes
* schannel: SSL/TLS connection with api.github.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with api.github.com port 443 (step 2/3)
* schannel: encrypted data got 3497
* schannel: encrypted data buffer: offset 3497 length 4096
* schannel: sending next handshake data: sending 64 bytes.
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with api.github.com port 443 (step 3/3)
* ALPN: server accepted http/1.1
* Didn't find Session ID in cache for host https://api.github.com:443
*    Subject: CN=*.github.com
*    Issuer: C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo ECC Domain Validation Secure Server CA
*    Version: 2
*    Serial Number: 00:8b:dc:0f:ff:54:77:2f:aa:d1:73:27:3f:23:36:2a:af:
* multi_done[CONNECTING]: status: 43 prem: 1 done: 0
* multi_done, not reusing connection=0, forbid=0, close=0, premature=1, conn_multiplex=0
* The cache now contains 0 members
* Curl_disconnect(conn #0, dead=1)
* Closing connection
* schannel: shutting down SSL/TLS connection with api.github.com port 443
* schannel: clear security context handle
* `

**Comment by dwstrong5** [comment] 2024-06-02 02:56
Running into same issue with Visual Studio 2022 and Windows 11. 
Code:
    
    cpr::Response r = cpr::Get(cpr::Url{ "https://api.github.com/repos/whoshuu/cpr/contributors" },
        cpr::Authentication{ "user", "pass", cpr::AuthMode::BASIC },
        cpr::Parameters{ {"anon", "true"}, {"key", "value"} },
        cpr::VerifySsl(false),
        cpr::Verbose(true));
    r.status_code;                  // 200
    r.header["content-type"];       // application/json; charset=utf-8
    r.text;                         // JSON text string

    std::cout << r.status_code << std::endl;
    return 0;


Verbose output:
 * !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => SETUP handle 0x25df2218cd8; line 1971
* STATE: SETUP => CONNECT handle 0x25df2218cd8; line 1987
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x25df2218cd8; line 2013
* Host api.github.com:443 was resolved.
* IPv6: (none)
* IPv4: 140.82.112.5
* STATE: RESOLVING => CONNECTING handle 0x25df2218cd8; line 2087
*   Trying 140.82.112.5:443...
* Connected to api.github.com (140.82.112.5) port 443
* schannel: SSL/TLS connection with api.github.com port 443 (step 1/3)
* Didn't find Session ID in cache for host https://api.github.com:443
* schannel: disabled server cert revocation checks
* schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: sending initial handshake data: sending 280 bytes.
* schannel: sent initial handshake data: sent 280 bytes
* schannel: SSL/TLS connection with api.github.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with api.github.com port 443 (step 2/3)
* schannel: encrypted data got 3497
* schannel: encrypted data buffer: offset 3497 length 4096
* schannel: sending next handshake data: sending 64 bytes.
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with api.github.com port 443 (step 3/3)
* ALPN: server accepted http/1.1
* Didn't find Session ID in cache for host https://api.github.com:443
*    Subject: CN=*.github.com
*    Issuer: C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo ECC Domain Validation Secure Server CA
*    Version: 2
*    Serial Number: 00:8b:dc:0f:ff:54:77:2f:aa:d1:73:27:3f:23:36:2a:af:
* multi_done[CONNECTING]: status: 43 prem: 1 done: 0
* multi_done, not reusing connection=0, forbid=0, close=0, premature=1, conn_multiplex=0
* The cache now contains 0 members
* Curl_disconnect(conn #0, dead=1)
* Closing connection
* schannel: shutting down SSL/TLS connection with api.github.com port 443
* schannel: clear security context handle

**Comment by COM8** [comment] 2024-06-02 04:34
This to me sound like an issue with linking to the Windows SSL lib (schannel). Could you please provide a small example project, so I can reproduce it? 
The following example works for me: https://github.com/libcpr/example-cmake-fetch-content

**Comment by dwstrong5** [comment] 2024-06-04 00:22
> This to me sound like an issue with linking to the Windows SSL lib (schannel). Could you please provide a small example project, so I can reproduce it? The following example works for me: https://github.com/libcpr/example-cmake-fetch-content

Odd, I cloned that example and ran it without issue. I try using the same main.cpp in a different project and ran into similar behavior in my original comment. Seems more like a config issue on my end. Hmm. Either way, thank you for the help!
