### ISSUE TITLE
Multi-part file uploading via buffer does not work properly.

### ISSUE THREAD

**Issue by ninearif** [libcpr/cpr#216] opened 2017-09-13 03:34 UTC
According to this feature  "Add support for POST file uploads from in-memory buffers " https://github.com/whoshuu/cpr/pull/129.

This support will allow you upload data from the buffer.
so when we do something like :

```
(1)
std::vector<unsigned char> content{'h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd'};
auto url = Url{"https://httpbin.org/post"};
auto response = cpr::Post(url, Multipart{
          { "fileContent", 
             Buffer{content.begin(), content.end(), "test_file.txt"}
          }});
```
 
and  :

```
(2)
std::vector<unsigned char> content{'h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd'};
auto url = Url{"https://httpbin.org/post"};
auto buff = Buffer{content.begin(), content.end(), "test_file.txt"};
auto response = cpr::Post(url, Multipart{
          { "fileContent", 
             buff
          }});
```

ps: I use httpbin.org to check my request details.

The expected behavior of POST request from both (1) and (2) should give the same result. They should be sent **fileContent** as a **file** not a **form** but only a code in (2) is work.The problem of (1) is  **fileContent** was sent as a **form** (It should be a **file**).

I'm not sure, I think this code might be related to this issue.

https://github.com/whoshuu/cpr/blob/b5758fbc88021437f968fe5174f121b8b92f5d5c/cpr/session.cpp#L29-L30
https://github.com/whoshuu/cpr/blob/b5758fbc88021437f968fe5174f121b8b92f5d5c/cpr/session.cpp#L184
https://github.com/whoshuu/cpr/blob/b5758fbc88021437f968fe5174f121b8b92f5d5c/cpr/session.cpp#L217

**Comment by ninearif** [comment] 2017-09-13 05:26
Here are request details that show a different result between code (1) and (2).
```
(1) Result:
{
  "args": {}, 
  "data": "", 
  "files": {
  }, 
  "form": {
    "fileContent": "....DATA....", 
  }, 
  "headers": {...}, 
  "json": null, 
  "origin": "...", 
  "url": "http://www.httpbin.org/post"
}
```

```
(2) Result:
{
  "args": {}, 
  "data": "", 
  "files": {
    "fileContent": "....DATA....", 
  }, 
  "form": {
  }, 
  "headers": {...}, 
  "json": null, 
  "origin": "...", 
  "url": "http://www.httpbin.org/post"
}
```

**Comment by Pwnsian** [comment] 2018-10-18 19:10
I'm also seeing similar behavior, with VS2017. But I can't reproduce (2) being sent as a file. Both are sent as a form for me. This is from the latest `master` and built without SSL support, if that matters.

@ninearif Are you seeing the same behavior reported in this issue with the latest commits?

**Comment by rkfg** [comment] 2018-12-29 07:58
I found the difference and it looks like a bug to me. To get the "files" result you need to pass the whole `cpr::Multipart` (not just the `cpr::Buffer`) by lvalue reference (didn't test this exact code): 
```cpp
auto parts = Multipart{ { "fileContent", Buffer{content.begin(), content.end(), "test_file.txt"} } };
auto response = cpr::Post(url, parts);
```
[When you pass by rvalue](https://github.com/whoshuu/cpr/blob/3d14e61ed247a90a07db26fb107beb3086a035d6/cpr/session.cpp#L183), it uses `CURLFORM_BUFFER` with `CURLFORM_COPYCONTENTS` and `CURLFORM_CONTENTSLENGTH`, those options don't play well together it seems. In particular, the request doesn't contain the filename field so the file contents are passed not as a file but as a simple string. The difference is very subtle (only the `filename` parameter in `Content-Disposition`) and you won't find it with `httpbin.org`, I had to use Wireshark for that.  If you use `CURLFORM_BUFFER` you need to use other `BUFFER*` options for it to work.

That's what happens when you [pass by lvalue](https://github.com/whoshuu/cpr/blob/3d14e61ed247a90a07db26fb107beb3086a035d6/cpr/session.cpp#L216), the code uses `CURLFORM_BUFFER`, `CURLFORM_BUFFERPTR` and `CURLFORM_BUFFERLENGTH` and the filename is actually included in the request.

I understand the author's intentions, you can't pass the pointer to an rvalue if it's going to outlive the rvalue itself, obviously, so you have to copy the rvalue contents somewhere. cURL provides such options but they behave inconsistently with a buffer being sent as a file. I'm not sure whose bug this is but in the meantime just use cpr::Multipart as an lvalue.

**Comment by ninearif** [comment] 2019-01-07 01:56
Thanks @rkfg

**Comment by cnSchwarzer** [comment] 2021-03-29 11:01
Please fix this, thanks, as the @rkfg mentioned passing by rvalue the 'filename' field doesn't show in the packet.
![image](https://user-images.githubusercontent.com/29846655/112827630-30fe6b80-90c1-11eb-96f0-18f34065b7c1.png)

**Comment by COM8** [comment] 2021-03-30 08:25
Would somebody like to create a workaround/fix PR for this?

**Comment by cnSchwarzer** [comment] 2021-04-05 13:36
@COM8 @rkfg  I don't understand why I can't pass an buffer pointer via an rvalue since the call is blocking, and there's no additional memory issue to worry about?

**Comment by GabrielMLB** [comment] 2021-05-18 14:15
Hello, I was wondering if it is possible to send an image (read with OpenCV) as a Buffer.

The code below passing only the image path worked, but I would like to send the image.

**What works**

```c
cpr::Response r = cpr::Post(cpr::Url{"http://localhost:8000/predict"}, cpr::Multipart{{"image_file", cpr::File{image_path}}});
```

**Comment by leviliangtw** [comment] 2022-04-02 17:28
I'd like to take this issue.

**Comment by KingKili** [comment] 2022-04-03 06:47
Sure go ahead. Just let me know when PR is ready. Thanks in advance!

**Comment by leviliangtw** [comment] 2022-06-16 14:21
@KingKili @COM8 
I tested it and now I think this issue is fixed by this commit: [Session cleanup. Fixes #479 · libcpr/cpr@96e33ba](https://github.com/libcpr/cpr/commit/96e33bae7a5282ae5a3cdac22c83499e0848d856#diff-cf37f7e6e7c606c16b02f59101a4b6e3c530806d97ce878cc22e35b8a15557ccR212)

**Comment by COM8** [comment] 2022-06-17 06:23
Even better! @leviliangtw could you have a look at creating a few unit tests for this "bug"?

**Comment by leviliangtw** [comment] 2022-06-17 07:04
> Even better! @leviliangtw could you have a look at creating a few unit tests for this "bug"?

Got it! No problem!

**Comment by leviliangtw** [comment] 2022-06-17 17:13
I created a new PR [#764](https://github.com/libcpr/cpr/pull/764).

**Closed** 2022-06-20 10:53 UTC
Labels: Bug :bug:, Needs Investigation :mag:
