### ISSUE TITLE
Makefile is not suitable for paths with spaces in it

### ISSUE THREAD

**Issue by Alex-Tsvetanov** [libcpr/cpr#727] opened 2022-04-17 15:57 UTC
## Description
Make is not able to execute if spaces (' ') are available in the path.

## Expected Behavior
Compilation to end successfully

## Actual Behavior
![image](https://user-images.githubusercontent.com/14363901/163722254-5a6c22cd-d566-493d-9d6a-04ca3397c5e8.png)

## Possible Fix
Add quotes in the generated Makefiles

## Steps to Reproduce
1. Run Windows with MinGW compiler
2. Run ``cmake -DCMAKE_BUILD_TYPE=Release -DCPR_BUILD_TESTS=ON -DCPR_FORCE_USE_SYSTEM_CURL=OFF . -G "Unix Makefiles"``
3. Run ``make MAKE=make CMAKE_COMMAND=cmake``

## Context
I cannot use the library at all.

## Your Environment

OS:
```
Edition         Windows 10 Pro N
Version         21H2
Installed on	‎8/‎13/‎2021
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
```
Compiler:
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\g++.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/11.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../src/configure --enable-languages=c,c++ --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-multilib --prefix=/c/temp/gcc/dest --with-sysroot=/c/temp/gcc/dest --disable-libstdcxx-pch --disable-libstdcxx-verbose --disable-nls --disable-shared --disable-win32-registry --enable-threads=posix --enable-libgomp --with-zstd=/c/mingw --disable-bootstrap
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (GCC)
```

**Comment by COM8** [comment] 2022-04-18 08:13
This looks like to be only a Windows Problem. On Linux I can not reproduce it.
To me this also looks like to be a zlib related issue. I will look into this roughly next weekend.

Is there a specific reason you need to use Makefiles for building?
Why not just something like this:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCPR_BUILD_TESTS=ON ..
cmake --build .
```

**Comment by KingKili** [comment] 2022-04-18 08:18
And the error message would help

18 Apr 2022 10:13:31 Fabian Sauter ***@***.***>:

**Comment by Alex-Tsvetanov** [comment] 2022-04-18 11:30
> And the error message would help 18 Apr 2022 10:13:31 Fabian Sauter ***@***.***>:

The error message in on the screenshot in Actual behavior section. If you need it in text format, I will have to download the library again so give me some time todo that.

> This looks like to be only a Windows Problem.
Yes, it is.

> Is there a specific reason you need to use Makefiles for building?
> Why not just something like this:
> ``cmake -DCMAKE_BUILD_TYPE=Release -DCPR_BUILD_TESTS=ON ..``
> ``cmake --build .``

I will try that. The reason why I used make is that I am not familiar with CMake's functionalities so I just when to the Arch's AUR PKGBUILD as I am used to working with Arch Linux and saw there the ``make`` command.

Some additional information after I tried to build curl-7.82.0 with ``cmake`` into ``make``. Similar issue appeared:
```
$ make
/usr/bin/sh: -c: line 0: syntax error near unexpected token `('
/usr/bin/sh: -c: line 0: `C:/Program Files (x86)/GnuWin32/bin/make -s -f CMakeFiles/Makefile2 all'
make: *** [all] Error 1
```
So keep in mind that the issue might not be related to the cpr project.

**Comment by Alex-Tsvetanov** [comment] 2022-04-18 22:25
FYI ``cmake --build .`` is not working either (the screenshot is from libcurl but it is the same error as with cpr
![image](https://user-images.githubusercontent.com/14363901/163887195-937dfd76-7991-4b62-8507-42bd7dd19a11.png)

**Comment by COM8** [comment] 2022-04-19 06:00
Why are you trying to build curl?
Could you please try building this example project:
https://github.com/libcpr/example-cmake-fetch-content

It does a great job showing how CMake works in this case.

**Comment by COM8** [comment] 2022-07-17 09:27
Any updates?

**Comment by COM8** [comment] 2022-08-01 07:28
Closing for now since no update. Feel free to reopen in case there is something new to it.

**Closed by COM8** 2022-08-01 07:28 UTC
Labels: Bug :bug:, Build :construction_worker:, Awaiting Resonse :hourglass_flowing_sand:, Windows :tv:
