### ISSUE TITLE
cpr library error: 'getaddrinfo() thread failed to start' running application in VRF

### ISSUE THREAD

**Issue by ChrisNelson-CyberReef** [libcpr/cpr#691] opened 2021-12-17 20:30 UTC
## Description

I'm writing an application that needs to access a remote REST API from a Linux (Ubuntu 20.04) system secured by Virtual Routing and Forwarding.

If I run my application no special setup, I'm unable to resolve the remote server by name.  This is an expected consequence of the server security.

If I run my application in the VRF environment by prefixing it with `ip vrf exec mgt`, I get the error in the summary, above.

I've tried a simple `curl https://google.com` and I see:

> $ curl https://google.com
> curl: (6) Could not resolve host: google.com
> $ sudo ip vrf exec mgt curl https://google.com
```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

So, the problem doesn't seem to be with `curl`.

## Expected Behavior

I expect to be able to resolve the remote server's FQDN

## Actual Behavior

cpr library error: 'getaddrinfo() thread failed to start'

## Steps to Reproduce

Try to `POST` with `cpr` within a VRF.

## Context

I can't resolve the remote server's FQDN.

## Your Environment
* Version used: 1.7.2, the same problem occurred with 1.6.2 which is why I upgraded
* Where did you get it from (e.g. conan, vcpkg, master, ...): a fork of cpr, checked out SHA beb9e98806bb84bcc130a2cebfbcbbc6ce62b335
* Operating System and version: Ubuntu 20.04
* Link to a small example:

**Comment by COM8** [comment] 2021-12-27 10:44
Thanks for reporting. I will have a look at this.

**Comment by COM8** [comment] 2021-12-28 08:08
Could you please give me some hints on how to set this up for testing?
Since when I run `ip vrf exec mgt curl https://google.com` I just get `Invalid VRF name`.

**Comment by ChrisNelson-CyberReef** [comment] 2022-01-03 14:44
> Could you please give me some hints on how to set this up for testing? Since when I run `ip vrf exec mgt curl https://google.com` I just get `Invalid VRF name`.

In  that command, `mgt` is the VRF name.  I didn't create our VRF and I'm not sure of the process but https://interpip.es/linux/creating-a-vrf-and-running-services-inside-it-on-linux/ may help.

**Comment by leviliangtw** [comment] 2022-07-27 08:16
@ChrisNelson-CyberReef @COM8 
I managed to create the VRF and a test program for this issue; however, I cannot reproduce the hostname resolution problem. 

The following is my environment: 

- OS version: Ubuntu 20.04 (5.15.0-41-generic)
- GCC version: 9.4.0
- Make version: 4.2.1
- Cmake version: 3.23.2
- iptables version: v1.8.4
- NIC: 
  - wlp3s0 (Realtek, built-in)
  - wlx908d788580df (D-Link, external)

The VRF settings: 

```shell
# Initialization of VRF "mgmt"
$ sudo ip link add mgmt type vrf table 1000
$ sudo ip link set dev mgmt up
$ sudo ip link set dev wlx908d788580df master mgmt

# Management of Rules
$ sudo ip -4 rule add pref 32765 table local
$ sudo ip -4 rule del pref 0
$ sudo ip -4 rule add pref 2000 dev unreachable

# Set up default route for vrf mgmt
$ sudo ip route add 192.168.0.1 dev wlx908d788580df
$ sudo ip route add table 1000 default via 192.168.0.1 dev wlx908d788580df

## Set up DNS resolution for vrf mgmt
$ sudo ip addr add 127.0.0.1/8 dev mgmt
$ sudo mv /etc/resolv.conf /etc/resolv.conf.bak
$ sudo sh -c 'grep nameserver /run/systemd/resolve/resolv.conf > /etc/resolv.conf'

# Test curl
$ curl google.com
$ sudo ip vrf exec mgmt curl google.com
```

The test CPR program:

```cpp
#include <iostream>
#include <cpr/cpr.h>

int main(int argc, char **argv)
{
    cpr::Response r = cpr::Get(cpr::Url{std::string(argv[1])});
    std::cout << r.status_code << std::endl;
    std::cout << r.header["content-type"] << std::endl;
    return 0;
}
```

Then I build the program and run it:

```shell
# Reach the internet using wlp3s0
$ ./build/main www.google.com
200
text/html; charset=ISO-8859-1

# Reach the internet using mgmt (wlx908d788580df)
$ sudo ip vrf exec mgmt ./build/main www.google.com
200
text/html; charset=ISO-8859-1
```

**Comment by ChrisNelson-CyberReef** [comment] 2022-07-27 17:28
> @ChrisNelson-CyberReef @COM8 I managed to create the VRF and a test program for this issue; however, I cannot reproduce the hostname resolution problem.
> ...

I'm sorry but we've switched to another solution and I no longer have an environment where I could try to reproduce this.

**Comment by COM8** [comment] 2022-07-28 14:57
Then I'm just closing this issue for now. In case someone else can reproduce this, we can reopen it again.
Thanks @leviliangtw for looking into this.

**Closed by COM8** 2022-07-28 14:57 UTC
Labels: Bug :bug:, curl :globe_with_meridians:
