### ISSUE TITLE
SetCookie just modify the header

### ISSUE THREAD

**Issue by dlee-libo** [libcpr/cpr#158] opened 2016-12-12 10:57 UTC
I noticed that the implementation of Session::SetCookie is based on CURLOPT_COOKIE. And from the document of libcurl: This option sets the cookie header explicitly in the outgoing request(s). If multiple requests are done due to authentication, followed redirections or similar, they will all get this cookie passed on. I think this behaviour is not what we expect although python's requests lib act the same. Or can we provide another API to initialize cookie engine?

**Comment by mexus** [comment] 2016-12-18 20:33
Could you please elaborate a little bit on this topic? some examples would certainly help..
actually what behaviour do you expect exactly?

**Comment by dlee-libo** [comment] 2016-12-19 04:52
The problem with CURLOPT_COOKIE is that it just change request headers. Take below code as an example.

client:
```cpp
cpr::Session s;
s.SetCookies({{"status", "off"}, {"name", "debug"}});
s.SetRedirect(true);
s.SetMaxRedirects(cpr::MaxRedirects{5});
s.SetUrl(cpr::Url{"http://127.0.0.1:9999"});
auto r = s.Get();
for (auto &kv : r.cookies) {
    std::cout << kv.first << std::endl;
}
```

server(nodejs snippets):
```javascript
var express = require('express');
var cookieParser = require('cookie-parser');
var app = express();
app.use(cookieParser());
var port = 9999;

app.get('/', (req, res)=> {
    console.log(req.headers);

    if (req.cookies.status == 'off') {
        res.writeHead(302, {
            'Location': 'http://127.0.0.1:' + port + '/',
            'Set-Cookie': 'status=on'
        });
        res.end();
    } else {
        res.end('hello');
    }

});

app.listen(port);

```

What we expect:
Client send get request to server with 'status=off;name=debug' in cookie.
Server respond with status 302 and set client's cookie to 'status=on'.
Client follow server's redirection, issue another request with 'status=on;name=debug' in cookie.
Server respond 'hello'. Client print 'name\nstatus'

What we really get:
Client send get request to server with 'status=off;name=debug' in cookie.
Server respond with status 302 and set client's cookie to 'status=on'.
Client follow server's redirection, issue another request with '**status=on; name=debug; status=off;** ' in cookie.
Server respond 'hello'. Client print '**status**'

According to RFC6265 section 4.2.2

> Although cookies are serialized linearly in the Cookie header,
   servers SHOULD NOT rely upon the serialization order.  In particular,
   if the Cookie header contains two cookies with the same name (e.g.,
   that were set with different Path or Domain attributes), servers
   SHOULD NOT rely upon the order in which these cookies appear in the
   header.

Which means behaviour in this example is not reliable.
Another problem is that we can't retrieve cookies set with CURLOPT_COOKIE, eg. the client only print 'status'

**Comment by COM8** [comment] 2020-06-22 15:01
Are there any suggestions how to change this?

**Comment by COM8** [comment] 2022-03-20 09:42
For this feature to be possible we have to refactor `cookies.h` and replace the internal `std::map<std::string, std::string>` with for example `std::map<std::string, cpr::Cookie>`. Pushing this back to the next release.

**Comment by leviliangtw** [comment] 2022-04-02 17:29
I'd like to take this issue.

**Comment by KingKili** [comment] 2022-04-03 06:47
Sure go ahead. Just let me know when PR is ready. Thanks in advance!

**Comment by leviliangtw** [comment] 2022-06-24 14:24
Hi, I wrote a unit test using `libcurl` purely in order to investigate how to fix it. 

Server: 
```c++
mg_str* request_cookies;
if ((request_cookies = mg_get_http_header(msg, "Cookie")) == nullptr) {
    mg_http_send_error(conn, 400, "Cookie not found");
    return;
}
std::string cookie_str{request_cookies->p, request_cookies->len};

if (cookie_str.find("status=on;") == std::string::npos) {
    std::cout << "[Server] Cookies received when \"status=off\": \"";
    std::cout << cookie_str << "\"" << std::endl;

    std::string headers =
            "Content-Type: text/html\r\n"
            "Location: http://127.0.0.1:61936/redirection_with_changing_cookies.html\r\n"
            "Set-Cookie: status=on;";

    mg_send_head(conn, 302, 0, headers.c_str());
    mg_send(conn, NULL, 0);
} else {
    std::cout << "[Server] Cookies received when \"status=on\": \"";
    std::cout << cookie_str << "\"" << std::endl;

    cookie_str = "hello";
    std::string headers = "Content-Type: text/html;";
    mg_send_head(conn, 200, cookie_str.length(), headers.c_str());
    mg_send(conn, cookie_str.c_str(), cookie_str.length());
}
```

Client: 
```c++
CURL* curl;
CURLcode res;
char errbuf[CURL_ERROR_SIZE];


curl = curl_easy_init();
if (curl) {
    // Common settings
    curl_easy_setopt(curl, CURLOPT_URL, "http://127.0.0.1:61936/redirection_with_changing_cookies.html");
    curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errbuf);
    curl_easy_setopt(curl, CURLOPT_HTTPGET, 1L);

    // Redirection settings
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 5L);
    curl_easy_setopt(curl, CURLOPT_UNRESTRICTED_AUTH, 0L);

    // Cookies settings
    curl_easy_setopt(curl, CURLOPT_COOKIEFILE, "");
    curl_easy_setopt(curl, CURLOPT_COOKIELIST, "ALL");
    curl_easy_setopt(curl, CURLOPT_COOKIE, "status=off; name=debug;");

    std::cout << "[Client] Start Perform" << std::endl;
    errbuf[0] = 0;
    res = curl_easy_perform(curl);
    std::cout << std::endl;
    std::cout << "[Client] End Perform" << std::endl;

    if (res != CURLE_OK) {
        size_t len = strlen(errbuf);
        fprintf(stderr, "\nlibcurl: (%d) ", res);
        if (len)
            fprintf(stderr, "%s%s", errbuf, ((errbuf[len - 1] != '\n') ? "\n" : ""));
        else
            fprintf(stderr, "%s\n", curl_easy_strerror(res));
    }
    curl_easy_cleanup(curl);
} else {
    std::cerr << "Couldnt easy_init" << std::endl;
}
```

The outputs: 
```shell
[Client] Start Perform
[Server] Cookies received when "status=off": "status=off; name=debug;"
[Server] Cookies received when "status=on": "status=on; status=off; name=debug;"
hello
[Client] End Perform
```

It seems that the unexpected behavior lies in the implementation of `libcurl`, so currently, I still haven't come up with a good idea for this issue. 
Does anyone have hints or some good ideas for this issue?

**Comment by COM8** [comment] 2022-06-25 09:11
I will have a look at it on Monday, since I'm currently not at home. But thanks for looking into it @leviliangtw !

**Comment by COM8** [comment] 2022-06-27 20:03
Yes, I agree this is a curl "issue". But I don't think this is a issue since in my eyes curl should not combine those two cookies into one. This is the task of the server. The server first should remove the old cookie and then set the new one.

So in my eyes this is nothing we can/should fix to prevent breaking the work flow of others needing such a behaviour.

@leviliangtw In my eyes we can/should close this issue or do you see this differently?

**Comment by leviliangtw** [comment] 2022-06-28 00:43
@COM8 Yes, I agree with you, and I don't see any difference. 
By the way, are you going to report this issue to `curl`? Or just let me report it?

**Comment by COM8** [comment] 2022-06-28 07:01
In my eyes this is also no issue in curl, since it's a server side "problem".

**Closed by COM8** 2022-06-28 07:01 UTC
Labels: Bug :bug:
